### ISSUE TITLE
HTML output instead of JSON

### ISSUE THREAD

**Issue by akamedia** [CygnusNetworks/nagios-plugin-graylog2#4]
Related issue:
https://github.com/CygnusNetworks/nagios-plugin-graylog2/issues/2

I am still getting error: 
GRAYLOG2CHECK UNKNOWN: RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded

ngrep -d eth0 port 9000
returns HTML output 
HTTP/1.1 200 OK..X-Graylog-Node-ID: ............................ </body>.</html>.

running check_graylog2 with option -v (verbose) gives a lot of errors:
GRAYLOG2CHECK UNKNOWN: RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 43, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/check_graylog2.py", line 177, in main
    check.main(verbose=args.verbose)
  File "/usr/lib/python2.7/site-packages/nagiosplugin/check.py", line 120, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 130, in execute
    self.run(check)
  File "/usr/lib/python2.7/site-packages/nagiosplugin/runtime.py", line 117, in run
    check()
  File "/usr/lib/python2.7/site-packages/nagiosplugin/check.py", line 105, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python2.7/site-packages/nagiosplugin/check.py", line 79, in _evaluate_resource
    for metric in metrics:
  File "build/bdist.linux-x86_64/egg/check_graylog2.py", line 77, in probe
    system = self.get_api_data('/system')
  File "build/bdist.linux-x86_64/egg/check_graylog2.py", line 114, in get_api_data
    return self.__get_json(uri)
  File "build/bdist.linux-x86_64/egg/check_graylog2.py", line 140, in __get_json
    raise RuntimeError("Graylog2 API returned non-JSON value: %s" % str(msg))
RuntimeError: Graylog2 API returned non-JSON value: No JSON object could be decoded

Can you help?

**Comment by akamedia** [comment]
Further to the above
When I add a url of "RAW" graylog2 I get:

ngrep -d eth0 port 9000
 HTTP/1.1 200 OK..Access-Control-Allow-Origin: *..Access-Control-Allow-Metho
  ds: GET..Access-Control-Allow-Headers: Content-Type, api_key, Authorization
  ..X-Graylog-Node-ID: 29842938462139462938429384 (other stuff follows)

The error I get from the command line:
KeyError: 'version'

What am I doing wrong here?

**Comment by p3dda** [comment]
Hi,

The check must be run against the graylog2 API, it seems you are running it against the web interface instead.

If you are running the API and web interface on the same port, you need to provide the configured API URL prefix to the nagios plugin (default: /api) http://docs.graylog.org/en/2.4/pages/configuration/web_interface.html

If your graylog2 configuration is the default configuration, the plugin call should be like:
`check_graylog2 -p 9000 --url /api -H ... `

What version of Graylog2 are you using? Can you provide the commandline of the check_graylog2 call and the full ngrep capture of the API request and response?

**Comment by akamedia** [comment]
As requested:
check_graylog2 -v -u user --password pass -H 10.1.0.1 -p 9000 --url /api/apidocs/streams/alerts/paginated

ngrep -d eth0 port 9000

interface: eth0 (192.168.1.0/255.255.255.0)
filter: ( port 9000 ) and ((ip || ip6) || (vlan && (ip || ip6)))
##
T 10.1.0.1:9000 -> 192.168.1.1:53264 [AS]
  ..
##
T 192.168.1.1:53264 -> 10.1.0.1:9000 [AP]
  GET /api/api-docs/streams/alerts/paginated/system HTTP/1.1..Accept-Encoding: identity..Host: 10.1.0.1:9000..Connection: close..User-Agent: Python-urllib/2.7....
#
T 10.1.0.1:9000 -> 192.168.1.1:53264 [A]
  ......
#
T 10.1.0.1:9000 -> 192.168.1.1:53264 [AFP]
  HTTP/1.1 200 OK..Access-Control-Allow-Origin: *..Access-Control-Allow-Methods: GET..Access-Control-Allow-Headers: Content-Type, api_key, Autho
  rization..X-Graylog-Node-ID: 5896e89d-ac29-4dc4-837f-47e9bec2b606..X-Runtime-Microseconds: 3581..Content-Type: application/json..Date: Mon, 22
   Jan 2018 14:42:40 GMT..Connection: close..Content-Length: 174....{"models":{},"apiVersion":"2.2.4-SNAPSHOT+1a3294a","swaggerVersion":"1.2","a
  pis":[],"basePath":"http://10.1.0.1:9000/api","resourcePath":"/streams/alerts/paginated/system"}
##
T 10.1.0.1:9000 -> 192.168.1.1:53264 [A]
  ......
exit
8 received, 0 dropped

**Comment by akamedia** [comment]
Can anyone post typical usage for this plugin?  Also a typical output for "critical/warning/good"?
